### ISSUE TITLE
NodeJS server -- Index page / -- throw an error on GET request

### ISSUE THREAD

**Issue by earthquakesan** [pyvandenbussche/sparqles#36]
I'm running the server with
$node app.js (didn't change any configs, server is running on 3001 port, MongoDB got populated with test data no problem)

GET /
/home/ivan/Workspace/java/sparqles/node/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: Cannot read property 'interoperability' of null
    at /home/ivan/Workspace/java/sparqles/node/app.js:41:56
    at /home/ivan/Workspace/java/sparqles/node/mongodbprovider.js:148:16
    at /home/ivan/Workspace/java/sparqles/node/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
    at /home/ivan/Workspace/java/sparqles/node/node_modules/mongodb/lib/mongodb/cursor.js:758:35
    at Cursor.close (/home/ivan/Workspace/java/sparqles/node/node_modules/mongodb/lib/mongodb/cursor.js:989:5)
    at Cursor.nextObject (/home/ivan/Workspace/java/sparqles/node/node_modules/mongodb/lib/mongodb/cursor.js:758:17)
    at commandHandler (/home/ivan/Workspace/java/sparqles/node/node_modules/mongodb/lib/mongodb/cursor.js:727:14)
    at /home/ivan/Workspace/java/sparqles/node/node_modules/mongodb/lib/mongodb/db.js:1916:9
    at Server.Base._callHandler (/home/ivan/Workspace/java/sparqles/node/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /home/ivan/Workspace/java/sparqles/node/node_modules/mongodb/lib/mongodb/connection/server.js:481:18

**Comment by pyvandenbussche** [comment]
This error is due to the fact that the aggregated data for the index page are not computed and therefore not available in MongoDB. 
Will create a new issue to add small data set to populate MongoDB so data would be available for the first deployment.
