### ISSUE TITLE
TypeError: Cannot read property 'interoperability' of undefined

### ISSUE THREAD

**Issue by berezovskyi** [pyvandenbussche/sparqles#52]
Trace:

```
500 TypeError: Cannot read property 'interoperability' of undefined
at /Users/andrew/code/sparqles/node/app.js:46:63
at /Users/andrew/code/sparqles/node/mongodbprovider.js:157:19
at /Users/andrew/code/sparqles/node/mongodbprovider.js:16:17
at Db.collection (/Users/andrew/code/sparqles/node/node_modules/mongodb/lib/mongodb/db.js:534:27)
at MongoDBProvider.getCollection (/Users/andrew/code/sparqles/node/mongodbprovider.js:15:11)
at MongoDBProvider.getAMonths (/Users/andrew/code/sparqles/node/mongodbprovider.js:156:10)
at /Users/andrew/code/sparqles/node/app.js:44:27
at /Users/andrew/code/sparqles/node/mongodbprovider.js:144:19
at /Users/andrew/code/sparqles/node/mongodbprovider.js:16:17
at Db.collection (/Users/andrew/code/sparqles/node/node_modules/mongodb/lib/mongodb/db.js:534:27)
```

Versions:

* commit 69b017a 
* mongo 3.2.10
* node 7.0.0
* [yarn](https://github.com/yarnpkg/yarn) instead of npm, but it shouldn't matter.

**Comment by berezovskyi** [comment]
After initialising the database, there is a record in the `index` collection and only one (as `MongoDBProvider.prototype.getIndex` is requesting).

<img width="618" alt="screen shot 2016-11-05 at 20 40 19" src="https://cloud.githubusercontent.com/assets/64734/20033055/39c93d82-a398-11e6-8d63-0ca5adda500a.png">

**Comment by berezovskyi** [comment]
I managed to resolve _that particular_ error by switching the mongo driver from 1.4.x to 2.0.x (given that I have mongodb 3.2.10), but there are more errors. I will make a PR for the fixed I made.
