### ISSUE TITLE
Server is down ?? 

### ISSUE THREAD

**Issue by momo54** [pyvandenbussche/sparqles#65]
Accessing : http://sparqles.ai.wu.ac.at/

I got:

```
Express
500 TypeError: Cannot read property 'interoperability' of undefined
at /usr/local/sparqles/node/app.js:46:63
at /usr/local/sparqles/node/mongodbprovider.js:157:19
at /usr/local/sparqles/node/mongodbprovider.js:16:17
at Db.collection (/usr/local/sparqles/node/node_modules/mongodb/lib/mongodb/db.js:534:27)
at MongoDBProvider.getCollection (/usr/local/sparqles/node/mongodbprovider.js:15:11)
at MongoDBProvider.getAMonths (/usr/local/sparqles/node/mongodbprovider.js:156:10)
at /usr/local/sparqles/node/app.js:44:27
at /usr/local/sparqles/node/mongodbprovider.js:144:19
at /usr/local/sparqles/node/mongodbprovider.js:16:17
at Db.collection (/usr/local/sparqles/node/node_modules/mongodb/lib/mongodb/db.js:534:27)
```

**Comment by TallTed** [comment]
FWIW, it's back, at least as of today.

**Comment by dssib** [comment]
Hi,

Is the server still maintained? This is an old issue, but the same error seems to be back there now.

**Comment by berezovskyi** [comment]
https://sparqles.demo.openlinksw.com/ is up and running.

My fork (https://github.com/berezovskyi/sparqles/releases) and their fork of my fork (https://github.com/OpenLinkSoftware/sparqles) are most recent/maintained.
